const basicWords = [
  'a', 'I', 'an', 'at', 'as',
  'be', 'by', 'do', 'go', 'if',
  'he', 'it', 'is', 'me', 'my',
  'no', 'of', 'on', 'or', 'up',
  'we', 'am', 'can', 'get', 'had',
  'has', 'her', 'his', 'how', 'its',
  'let', 'man', 'may', 'not', 'one',
  'out', 'see', 'she', 'the', 'too',
  'was', 'you', 'all', 'any', 'but',
  'for', 'and', 'that', 'them', 'they',
  'this', 'your', 'what', 'when', 'where',
  'will', 'with', 'just', 'know', 'like',
  'time', 'take', 'come', 'make', 'read',
  'find', 'more', 'back', 'give', 'even',
  'said', 'over', 'only', 'just', 'into',
  'upon', 'then', 'also', 'here', 'than',
  'very', 'some', 'most', 'much', 'same',
  'next', 'part', 'mean', 'give', 'land',
  'hand', 'tell', 'used', 'call', 'work',
  'feel', 'look', 'keep', 'live', 'play',
  'call', 'fall', 'take', 'sent', 'land',
  'roll', 'bear', 'heat', 'wish', 'hope',
  'road', 'lamp', 'star', 'home', 'fire',
  'door', 'head', 'back', 'head', 'face',
  'blue', 'test', 'bath', 'club', 'task',
  'ship', 'park', 'well', 'mine', 'task',
  'edge', 'wave', 'rush', 'kind', 'mind',
  'soul', 'wish', 'baby', 'long', 'free',
  'kind', 'tree', 'grow', 'face', 'leaf',
  'news', 'door', 'club', 'gear', 'cord',
  'band', 'lone', 'kind', 'tile', 'pale',
  'rose', 'step', 'wake', 'race', 'gold',
  'bark', 'play', 'cool', 'need', 'link',
  'mind', 'deal', 'turn', 'tone', 'pull',
  'stop', 'pull', 'chip', 'bear', 'bowl',
  'high', 'shot', 'pick', 'wait', 'full',
  'tank', 'talk', 'ball', 'road', 'fast',
  'bill', 'date', 'time', 'help', 'seat',
  'heat', 'soft', 'kind', 'hard', 'dark',
  'rush', 'deed', 'grip', 'trip', 'wave',
  'nest', 'ring', 'golf', 'bowl', 'tale',
  'debt', 'load', 'game', 'face', 'feel',
  'pass', 'call', 'move', 'glow', 'dare',
  'list', 'blue', 'firm', 'last', 'cost',
  'wait', 'kick', 'burn', 'yarn', 'fade',
  'date', 'bear', 'hide', 'play', 'stay',
  'pull', 'mood', 'find', 'wake', 'ball',
  'live', 'pain', 'lake', 'zoom', 'walk',
  'kill', 'miss', 'rule', 'hunt', 'hill',
  'unit', 'warp', 'wish', 'wild', 'grip',
  'rock', 'milk', 'beat', 'time', 'card',
  'blow', 'edge', 'turn', 'head', 'warm',
  'more', 'pair', 'hurt', 'bump', 'mask',
  'pale', 'peel', 'pond', 'seat', 'kind',
  'edge', 'foot', 'past', 'fall', 'calm',
  'bark', 'fast', 'back', 'clap', 'bold',
  'disk', 'fade', 'cure', 'ring', 'bead',
  'boat', 'hole', 'last', 'palm', 'firm',
  'mile', 'dust', 'gate', 'fold', 'tune',
  'cage', 'pond', 'farm', 'list', 'barn',
  'spot', 'dish', 'park', 'land', 'bend',
  'life', 'yard', 'gift', 'meal', 'book',
  'ring', 'fork', 'jump', 'mate', 'tide',
  'coat', 'bead', 'line', 'test', 'cool',
  'card', 'hole', 'move', 'neck', 'pair',
  'cost', 'bare', 'bear', 'flap', 'wave',
  'gaze', 'soft', 'term', 'leaf', 'link',
  'card', 'palm', 'milk', 'seal', 'grab',
  'land', 'fade', 'hill', 'term', 'lead',
  'puff', 'view', 'tile', 'coat', 'cane',
  'bond', 'film', 'cafe', 'hold', 'lamp',
  'fawn', 'bone', 'come', 'edge', 'grow',
  'inch', 'play', 'base', 'near', 'rose',
  'bake', 'root', 'fall', 'dust', 'slow',
  'sail', 'tent', 'mild', 'tale', 'mood',
  'bold', 'base', 'maze', 'chip', 'milk',
  'crew', 'call', 'rock', 'kill', 'zone',
  'cold', 'care', 'cafe', 'bank', 'cane',
  'disk', 'fold', 'bowl', 'cook', 'root',
  'game', 'gear', 'find', 'hope', 'loop',
  'bear', 'gate', 'cane', 'case', 'task',
  'risk', 'band', 'fold', 'tone', 'mark',
  'well', 'corn', 'jump', 'race', 'turn',
  'news', 'fire', 'kite', 'mind', 'wind',
  'deck', 'star', 'cool', 'wave', 'full',
  'tent', 'maze', 'look', 'hand', 'type',
  'file', 'goal', 'time', 'hill', 'note',
  'bump', 'kick', 'mice', 'blow', 'turn',
  'hike', 'chip', 'unit', 'jump', 'bark'
];


const advancedWords = [
  'abandon', 'abnormal', 'absolute', 'abundance', 'academic',
  'accumulate', 'achievement', 'acquisition', 'adventure', 'advocate',
  'affection', 'aggressive', 'allegiance', 'anxiety', 'apparent',
  'artificial', 'assignment', 'association', 'attraction', 'audience',
  'authority', 'automatic', 'awareness', 'beneficial', 'biography',
  'calculation', 'challenge', 'character', 'cognition', 'compassion',
  'conclusion', 'conflict', 'connection', 'consequence', 'contribute',
  'creativity', 'criticism', 'definition', 'democracy', 'development',
  'discovery', 'education', 'emergency', 'emotionally', 'emphasis',
  'encounter', 'enthusiasm', 'essentially', 'evaluation', 'exaggerate',
  'experience', 'expression', 'extraction', 'fascinating', 'feedback',
  'frequency', 'generosity', 'government', 'guideline', 'happiness',
  'immediate', 'impression', 'importance', 'independent', 'influence',
  'innovation', 'inspiration', 'integration', 'intelligent', 'intention',
  'investigate', 'knowledgeable', 'legislation', 'limitation', 'literature',
  'maintenance', 'management', 'motivation', 'negotiation', 'observation',
  'opportunity', 'organization', 'participation', 'perception', 'persuasion',
  'policymaker', 'prediction', 'preference', 'professional', 'promotion',
  'psychology', 'reaction', 'relationship', 'representation', 'revolution',
  'satisfaction', 'significance', 'solution', 'strategy', 'technology',
  'transformation', 'universal', 'utilization', 'validation', 'volunteer',
  'abstraction', 'absorption', 'acceleration', 'adolescent', 'affiliation',
  'agriculture', 'alternation', 'application', 'approximate', 'articulate',
  'attraction', 'authorization', 'calculation', 'celebration', 'characteristic',
  'circulation', 'classification', 'collaboration', 'comprehensive', 'concentration',
  'conventional', 'cooperation', 'declaration', 'demonstration', 'determination',
  'developmental', 'discrimination', 'documentation', 'evaluation', 'examination',
  'expectation', 'explanation', 'formulation', 'foundation', 'generalization',
  'globalization', 'implication', 'implementation', 'improvement', 'infrastructure',
  'intellectual', 'interpretation', 'introduction', 'investigation', 'manipulation',
  'negotiation', 'observation', 'organization', 'partnership', 'perspective',
  'presentation', 'procrastination', 'qualification', 'realization', 'recommendation',
  'reorganization', 'representation', 'responsibility', 'satisfaction', 'speculation',
  'standardization', 'transformation', 'transportation', 'utilization', 'verification',
  'abduction', 'abominable', 'abolition', 'accusation', 'advantageous',
  'affliction', 'ambiguous', 'anomaly', 'aristocrat', 'astonishing',
  'atmosphere', 'autonomy', 'collaboration', 'compromised', 'conventional',
  'correlation', 'deviation', 'disregard', 'divergence', 'emancipation',
  'exceptional', 'exclamation', 'fascination', 'foreclosure', 'glamorous',
  'illustration', 'imagination', 'implementation', 'influential', 'intelligent',
  'intolerance', 'investigation', 'manipulation', 'metaphorically', 'notification',
  'obligation', 'predicament', 'professionally', 'representation', 'reverberate',
  'spontaneous', 'suspicious', 'transcendence', 'unfamiliar', 'unfortunate',
  'abominable', 'adaptation', 'adventurous', 'advantageous', 'allegation',
  'apprehensive', 'characteristic', 'characteristically', 'clarification', 'complicated',
  'congruently', 'deformation', 'determination', 'disadvantage', 'dissatisfaction',
  'distribution', 'enlightenment', 'exaggeration', 'exclamation', 'impressionable',
  'individualistic', 'inquisition', 'involuntary', 'irrationally', 'justification',
  'malfunctioning', 'misanthropic', 'miscommunication', 'misinterpretation', 'narration',
  'notification', 'orientation', 'reassurance', 'recollection', 'satisfaction',
  'sophisticated', 'speculation', 'spontaneity', 'symbolization', 'therapeutic',
  'translucent', 'vulnerability', 'advancement', 'accountability', 'adaptability',
  'apprehension', 'appropriation', 'assassination', 'attractiveness', 'circumference',
  'clarification', 'collaboration', 'concentration', 'congratulation', 'consequential',
  'deterioration', 'determination', 'exhilaration', 'generalization', 'hospitalization',
  'hypothetical', 'imagination', 'implementation', 'improvement', 'independence',
  'interruption', 'investigation', 'legislation', 'notification', 'overwhelming',
  'parliamentary', 'participation', 'persuasion', 'proclamation', 'publication',
  'qualification', 'recollection', 'reimbursement', 'relationship', 'reinforcement',
  'revelation', 'satisfaction', 'simplification', 'substantial', 'substantiation',
  'understanding', 'unfortunate', 'verification', 'voluntary'
];


const quotes = [
  'The cat jumped over the fence.',
  "I can't believe we won the game!",
  'The cake was delicious, but too sweet for my taste.',
  'Can you hear that noise coming from the attic?',
  'She opened the door and found a surprise waiting for her.',
  'Why did the chicken cross the road?',
  "It's a beautiful day outside, isn’t it?",
  'The movie was longer than I expected, but it was worth it.',
  'He walked his dog every morning without fail.',
  'I forgot my umbrella, and now I’m soaked!',
  'Do you remember when we visited the beach last summer?',
  'She loves to paint landscapes, especially in the fall.',
  'The book on the shelf caught my eye immediately.',
  'I enjoy reading novels, particularly mysteries and thrillers.',
  'He always wears that old baseball cap, no matter the occasion.',
  'The music at the party was too loud to have a conversation.',
  'My favorite color has always been blue, since childhood.',
  'After dinner, we played board games until midnight.',
  'She couldn’t stop laughing at the funny video.',
  'The flowers in the garden are blooming beautifully this spring.',
  'Have you seen the latest episode of that series?',
  'The little boy was fascinated by the magician’s tricks.',
  'I love to watch the sunset over the ocean.',
  'He found a wallet on the ground and turned it in.',
  'Her smile brightened the room instantly.',
  'We should plan a trip to the mountains next year.',
  'The computer crashed while I was working on my project.',
  'He made a fantastic impression during the interview.',
  'She took a deep breath before stepping onto the stage.',
  'The teacher assigned us a challenging project for the weekend.',
  'It’s amazing how quickly time flies when you’re having fun.',
  'The kids were excited to go to the amusement park.',
  'They discovered a hidden path in the forest during their hike.',
  'He often talks about his travels around the world.',
  'The stars were shining brightly in the night sky.',
  'She spent the afternoon baking cookies for her friends.',
  'The coffee shop on the corner has the best pastries.',
  'He was surprised by the unexpected turn of events.',
  'The rain poured down, creating puddles on the street.',
  'I’ve never seen such a beautiful rainbow before.',
  'The sound of the waves crashing on the shore was soothing.',
  'He enjoyed his time volunteering at the animal shelter.',
  'The children played happily in the park.',
  'She found an old photograph hidden in a drawer.',
  'The train arrived at the station right on time.',
  'I need to buy groceries before the store closes.',
  'The dog barked excitedly when its owner returned home.',
  'She decided to take a different route to work today.',
  'The neighborhood was quiet except for the sound of birds.',
  'He worked hard to finish the project ahead of the deadline.',
  'The delicious aroma of freshly baked bread filled the air.',
  'They laughed together, reminiscing about their childhood.',
  'The street was bustling with people and activity.',
  'She received an award for her outstanding performance.',
  'He spent the afternoon reading by the fireplace.',
  'The storm passed quickly, leaving behind clear skies.',
  'They enjoyed a picnic in the park on a sunny day.',
  'She always carries a notebook to jot down her ideas.',
  'The mountain view was breathtaking and worth the hike.'
];


// Exporting all arrays for use in other modules
export { basicWords, advancedWords, quotes };
